import {useCallback,useEffect,useRef,useState} from 'react';
import {BookOpen,Check,Cloud,NotebookPen,RotateCcw,Settings2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogTrigger} from '@/components/ui/dialog';
import PdfViewer from './PdfViewer';
import data from './study-data.json';
import {cloud,getRecord,saveRecord,RecordData} from './storage';
const fresh=():RecordData=>({answer:'',notes:'',status:'new',updated_at:new Date().toISOString()});
const labels={new:'아직 공부 중',review:'다시 보기',done:'복습 완료'};
export default function App(){
 const [category,setCategory]=useState('major');const [examId,setExamId]=useState('mock2');const [paperIndex,setPaperIndex]=useState(0);const [pageIndex,setPageIndex]=useState(0);
 const [reference,setReference]=useState(false);const [refIndex,setRefIndex]=useState(0);const [refPage,setRefPage]=useState(0);const [version,setVersion]=useState(0);
 const [user,setUser]=useState<any>(null);const [email,setEmail]=useState('');const [authMsg,setAuthMsg]=useState('');const [loginBusy,setLoginBusy]=useState(false);
 const [record,setRecord]=useState<RecordData>(fresh);const [loaded,setLoaded]=useState(false);const [saveState,setSaveState]=useState('불러오는 중…');const [dirty,setDirty]=useState(false);const [reviewList,setReviewList]=useState<any[]>([]);const [reviewsOpen,setReviewsOpen]=useState(false);
 const latest=useRef(record);const dirtyRef=useRef(false);const generation=useRef(0);const saving=useRef<Promise<boolean>|null>(null);const editVersion=useRef(0);
 const exam=data.find(e=>e.id===examId)!;const paper=exam.papers[paperIndex];const page=paper.pages[pageIndex];const ref=exam.references[refIndex];const uid=user?.id||'guest';const recordKey=`${examId}:${paper.id}:${page.page}`;
 useEffect(()=>{if(!cloud)return;cloud.auth.getSession().then(({data})=>setUser(data.session?.user??null));const {data:subscription}=cloud.auth.onAuthStateChange((_e,s)=>setUser(s?.user??null));return()=>subscription.subscription.unsubscribe()},[]);
 useEffect(()=>{let alive=true;generation.current++;setLoaded(false);setDirty(false);dirtyRef.current=false;setRecord(fresh());setSaveState('불러오는 중…');getRecord(uid,recordKey).then(({record:r,offline})=>{if(!alive)return;const value=r||fresh();latest.current=value;setRecord(value);setLoaded(true);setSaveState(offline?'연결 실패 · 이 기기의 초안 표시':user?'계정 기록을 불러왔어요':'이 기기의 임시 초안');}).catch(()=>{if(alive){setLoaded(true);setSaveState('저장 공간을 열 수 없어요. 작성한 답안은 복사해 보관하세요.')}});return()=>{alive=false}},[uid,recordKey]);
 function edit(patch:Partial<RecordData>){const next={...latest.current,...patch,updated_at:new Date().toISOString()};latest.current=next;editVersion.current++;setRecord(next);setDirty(true);dirtyRef.current=true;setSaveState('저장 대기 중…')}
 const save=useCallback(async()=>{if(saving.current)await saving.current;if(!dirtyRef.current)return true;const rev=editVersion.current;const gen=generation.current;const snapshot={...latest.current};setSaveState('저장 중…');const p=(async()=>{try{const synced=await saveRecord(uid,recordKey,snapshot);if(gen===generation.current){if(rev===editVersion.current){dirtyRef.current=false;setDirty(false)}setSaveState(synced?'계정에 저장됨 · 다른 기기에서도 이어볼 수 있어요':'이 기기에 임시 저장됨 · 자동 동기화는 아직 꺼져 있어요')}return true}catch{if(gen===generation.current)setSaveState('동기화 실패 · 초안은 이 기기에 보관됨. 다시 저장해 주세요.');return false}})();saving.current=p;const ok=await p;saving.current=null;return ok},[uid,recordKey]);
 useEffect(()=>{if(!dirty||!loaded)return;const t=setTimeout(()=>{void save()},1100);return()=>clearTimeout(t)},[record,dirty,loaded,save]);
 useEffect(()=>{const leave=(e:BeforeUnloadEvent)=>{if(dirtyRef.current){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',leave);return()=>window.removeEventListener('beforeunload',leave)},[]);
 async function move(action:()=>void){if(dirtyRef.current&&!await save())return;action();setReference(false);setRefIndex(0);setRefPage(0)}
 function chooseExam(id:string){void move(()=>{setExamId(id);setPaperIndex(0);setPageIndex(0)})}
 async function login(e:React.FormEvent){e.preventDefault();if(!cloud)return;setLoginBusy(true);setAuthMsg('');const {error}=await cloud.auth.signInWithOtp({email,options:{emailRedirectTo:new URL(import.meta.env.BASE_URL,location.origin).href}});setLoginBusy(false);setAuthMsg(error?'로그인 메일을 보내지 못했어요: '+error.message:'메일의 로그인 링크를 눌러주세요. 두 기기에서 같은 이메일로 로그인하면 됩니다.')}
 async function openReviews(){setReviewsOpen(true);if(!cloud||!user){setReviewList([]);return}const {data:rows,error}=await cloud.from('study_records').select('record_key,status,updated_at').eq('user_id',user.id).eq('status','review').order('updated_at',{ascending:false});if(error){setSaveState('복습 목록을 불러오지 못했어요.');return}setReviewList(rows||[])}
 async function jump(key:string){const [eId,pId,pNo]=key.split(':');const e=data.find(e=>e.id===eId);const pi=e?.papers.findIndex(p=>p.id===pId)??-1;const pgi=pi>=0?e!.papers[pi].pages.findIndex(p=>p.page===Number(pNo)):-1;if(!e||pi<0||pgi<0)return;await move(()=>{setCategory(e.category);setExamId(e.id);setPaperIndex(pi);setPageIndex(pgi);setReviewsOpen(false)})}
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const control=new AbortController();try{Promise.resolve(context.registerTool({name:'read_study_position',description:'현재 선택한 시험과 문제지 쪽, 저장 상태를 읽습니다. 답안을 변경하지 않습니다.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('입력 항목이 없어야 합니다.');return {exam:exam.title,paper:paper.label,page:page.page,status:latest.current.status}}},{signal:control.signal})).catch(()=>{})}catch{}return()=>control.abort()},[examId,paperIndex,pageIndex]);
 return <div className="study-app">
 <header className="topbar"><div className="brand-mark"><BookOpen size={23}/></div><strong>나의 임용 공부방</strong><span className="private-label">교재는 내 기기에 · 기록은 내 계정에</span><Dialog><DialogTrigger asChild><Button variant="ghost" className="account-button"><Cloud size={17}/>{user?'내 계정':'동기화 연결'}</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>공부 기록 이어보기</DialogTitle><DialogDescription>교재 파일은 동기화하지 않고, 작성한 답안과 복습 기록만 계정에 저장합니다.</DialogDescription></DialogHeader>{!cloud?<div className="setup-note"><h3>저장 서비스 연결 준비 중</h3><p>사이트 설정에 Supabase 연결 정보가 아직 등록되지 않았어요. 현재 답안은 이 기기에 임시 보관됩니다.</p><p>연결이 끝나면 같은 이메일로 로그인해 휴대폰과 컴퓨터에서 이어볼 수 있어요.</p><a href="https://github.com/rani0380/jungccom/blob/main/SETUP.md" target="_blank" rel="noreferrer">연결 안내 보기</a></div>:user?<><p>{user.email}</p><p className="muted">다른 기기로 이동하기 전에 ‘계정에 저장됨’을 확인하세요. 두 기기에서 같은 답안을 동시에 수정하면 마지막 저장 내용이 반영됩니다.</p><Button variant="outline" onClick={async()=>{if(await save())await cloud.auth.signOut()}}>로그아웃</Button></>:<form onSubmit={login}><label htmlFor="email">로그인 이메일</label><input id="email" type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@example.com"/><Button disabled={loginBusy} type="submit">{loginBusy?'보내는 중…':'로그인 링크 받기'}</Button><p className="muted">로그인 전 임시 답안과 계정 답안은 별도로 보관됩니다. 필요한 임시 답안은 복사한 뒤 로그인해 주세요.</p></form>}<p role="status">{authMsg}</p></DialogContent></Dialog></header>
 <main><div className="page-heading"><div><p className="eyebrow">2027 임용 준비</p><h1>오늘도, 한 문제씩.</h1></div><div className="heading-side"><span>전공 모의고사와 교육학 기출 연습</span><Button variant="outline" onClick={openReviews}><RotateCcw size={16}/>다시 볼 문제지</Button></div></div>
 <Tabs value={category} onValueChange={v=>void move(()=>{setCategory(v);setExamId(v==='major'?'mock2':'edu2026');setPaperIndex(0);setPageIndex(0)})}><TabsList className="subject-tabs"><TabsTrigger value="major">전공 모의고사</TabsTrigger><TabsTrigger value="education">교육학 기출</TabsTrigger></TabsList></Tabs>
 <div className="selection-row"><div><label>시험 선택</label><Select value={examId} onValueChange={chooseExam}><SelectTrigger className="exam-select"><SelectValue/></SelectTrigger><SelectContent>{data.filter(e=>e.category===category).sort((a,b)=>category==='education'?b.title.localeCompare(a.title):0).map(e=><SelectItem value={e.id} key={e.id}>{e.title} {category==='major'?`· ${e.date}`:''}</SelectItem>)}</SelectContent></Select></div><div><label>시험지</label><div className="paper-buttons">{exam.papers.map((p,i)=><Button key={p.id} variant={paperIndex===i?'default':'outline'} onClick={()=>void move(()=>{setPaperIndex(i);setPageIndex(0)})}>{p.label}</Button>)}</div></div><div className="session-hint"><NotebookPen size={20}/><span>{category==='major'?'한 쪽씩 풀고, 모범답안으로 확인해요.':'개요부터 적어도 좋아요. 완성한 뒤 답안과 비교해요.'}</span></div></div>
 <div className="workbench"><section className="paper-panel"><div className="panel-heading"><div><p className="eyebrow">{category==='major'?'전공':'교육학'} / 문제지</p><h2>{exam.title} · {paper.label}</h2></div><span>{pageIndex+1} / {paper.pages.length}쪽</span></div><nav className="page-buttons" aria-label="문제지 쪽 선택">{paper.pages.map((p,i)=><Button key={p.page} variant={pageIndex===i?'default':'ghost'} aria-current={pageIndex===i?'page':undefined} onClick={()=>void move(()=>setPageIndex(i))}>{i+1}쪽</Button>)}</nav><PdfViewer fileKey={paper.fileKey} name={paper.sourceName} page={page.page} version={version} onImport={()=>setVersion(v=>v+1)}/><div className="bottom-nav"><Button variant="outline" disabled={pageIndex===0} onClick={()=>void move(()=>setPageIndex(i=>i-1))}>이전 쪽</Button><span className="muted">답안은 문제지 쪽별로 저장돼요.</span><Button variant="outline" disabled={pageIndex===paper.pages.length-1} onClick={()=>void move(()=>setPageIndex(i=>i+1))}>다음 쪽</Button></div></section>
 <section className="answer-panel"><div className="answer-title"><div><p className="eyebrow">나의 풀이</p><h2>{category==='education'?'개요와 답안 작성':'답안 작성'}</h2></div><span className={'status-pill '+record.status}>{labels[record.status]}</span></div><label className="sr-only" htmlFor="answer">답안</label><textarea id="answer" disabled={!loaded} maxLength={60000} value={record.answer} onChange={e=>edit({answer:e.target.value})} placeholder={category==='education'?'핵심 키워드와 개요부터 적어보세요.\n\n서론\n\n본론\n\n결론':'문항 번호와 함께 답안을 적어보세요.\n\n1번.\n\n2번.'}/><div className="answer-meta"><span>{record.answer.length.toLocaleString()}자</span><Button variant="outline" disabled={!loaded} onClick={()=>void save()}>답안 저장</Button></div><p className="save-status" role="status">{saveState}</p><Button className="reveal-button" variant={reference?'secondary':'default'} onClick={()=>setReference(!reference)}><BookOpen size={17}/>{reference?'모범답안 접기':'모범답안·강의노트 확인'}</Button><p className="muted small-note">제공된 답안과 직접 비교해요. 자동 채점하지 않습니다.</p><label htmlFor="notes" className="field-label">헷갈린 개념 · 다음에 기억할 것</label><textarea id="notes" className="notes-input" disabled={!loaded} value={record.notes} maxLength={20000} onChange={e=>edit({notes:e.target.value})} placeholder="틀린 이유를 한 줄만 남겨도 충분해요."/><div className="review-buttons"><Button disabled={!loaded} variant={record.status==='review'?'default':'outline'} onClick={()=>edit({status:record.status==='review'?'new':'review'})}><RotateCcw size={16}/>다시 보기</Button><Button disabled={!loaded} variant={record.status==='done'?'default':'outline'} onClick={()=>edit({status:record.status==='done'?'new':'done'})}><Check size={16}/>복습 완료</Button></div></section></div>
 {reference&&<section className="reference-panel"><div className="panel-heading"><div><p className="eyebrow">답안 비교</p><h2>{exam.title} · {ref.label}</h2></div><Button variant="ghost" onClick={()=>setReference(false)}>접기</Button></div><div className="reference-controls"><Select value={String(refIndex)} onValueChange={v=>{setRefIndex(Number(v));setRefPage(0)}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{exam.references.map((r,i)=><SelectItem value={String(i)} key={r.id}>{r.label}</SelectItem>)}</SelectContent></Select><Button variant="outline" disabled={refPage===0} onClick={()=>setRefPage(n=>n-1)}>이전</Button><Select value={String(refPage)} onValueChange={v=>setRefPage(Number(v))}><SelectTrigger aria-label="답안 쪽 선택"><SelectValue/></SelectTrigger><SelectContent>{ref.pages.map((p,i)=><SelectItem value={String(i)} key={p.page}>{i+1} / {ref.pages.length}쪽</SelectItem>)}</SelectContent></Select><Button variant="outline" disabled={refPage===ref.pages.length-1} onClick={()=>setRefPage(n=>n+1)}>다음</Button></div><PdfViewer fileKey={ref.fileKey} name={ref.sourceName} page={ref.pages[refPage].page} version={version} onImport={()=>setVersion(v=>v+1)}/></section>}
 <footer>교재 원문은 사이트에 게시하지 않습니다. PDF는 각 기기에서 직접 선택해 주세요. {category==='education'&&'교육학 모범답안집 한 파일을 선택하면 연도별 해당 쪽이 열립니다.'}</footer></main>
 <Dialog open={reviewsOpen} onOpenChange={setReviewsOpen}><DialogContent><DialogHeader><DialogTitle>다시 볼 문제지</DialogTitle><DialogDescription>계정에 저장된 ‘다시 보기’ 목록입니다.</DialogDescription></DialogHeader>{!user?<p>동기화를 연결하고 로그인하면 모든 기기의 복습 목록을 모아볼 수 있어요.</p>:reviewList.length===0?<p>다시 볼 문제지가 없어요. 풀이 화면에서 ‘다시 보기’를 눌러보세요.</p>:<div className="review-list">{reviewList.map(r=>{const [id,pId,n]=r.record_key.split(':');const e=data.find(e=>e.id===id);return <Button variant="outline" key={r.record_key} onClick={()=>jump(r.record_key)}>{e?.title||id} · {e?.papers.find(p=>p.id===pId)?.label} · 원본 {n}쪽</Button>})}</div>}</DialogContent></Dialog>
 </div>
}
